version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbit'
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: 'some-rabbit'
  
  sqlserver:
    image: 'mcr.microsoft.com/azure-sql-edge'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password12*'
      MSSQL_PID: 'Developer'
    ports:
      - 1433:1433
    
